### ISSUE TITLE
Expose additional Syncthing ports

### ISSUE THREAD

**Issue by votdev** [openmediavault/openmediavault-k8s-recipes#39]
Right now only the UI is available through the reverse proxy. To get Syncthing fully functional the additional ports 21027 and 22000 need to be exposed.

**Comment by Holzhaus** [comment]
Hi @votdev, can you give me some pointers how to do this? I'm currently trying to build a recipe for mpd which exposes TCP port 6600 (for MPD) + two HTTP streams (for MP3 and FLAC). Due to the latter I would like to avoid `hostNetwork: true` and use the normal mechanism for HTTP, but I cannot get it working due the same issue with modifing the traefik config that I already encountered with #51 (i.e. that the UI becomes inaccessible).

<details><summary>YAML snippet</summary>

```yaml
# ... snip ...
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mpd-web
  namespace: mpd-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`mp3.mpd.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: mpd-stream-mp3
          port: 8081
    - match: Host(`flac.mpd.{{ fqdn() }}`)
      kind: Rule
      services:
        - name: mpd-stream-flac
          port: 8082
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mpd-tcp
  namespace: mpd-app
spec:
  entryPoints:
    - mpd
  routes:
    - match: HostSNI(`*`)
      services:
        - name: mpd-tcp
          port: 6060
  tls: {}
---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      mpd:
        port: 6060
        expose:
          default: true
        exposedPort: 6060
```
</details>

Is there a better way than repeating the entire `valuesContent` from `/var/lib/rancher/k3s/server/manifests/openmediavault-traefik.yaml`? That is cumbersome and doesn't scale when you have multiple recipies that like to add ports.

Thanks!
